<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:msxsl="urn:schemas-microsoft-com:xslt" xmlns:myjs="urn:custom-javascript" exclude-result-prefixes="msxsl myjs">
  <xsl:variable name="episodes" select="//tokens/token[@name='%EPISODELIST%']"/>
  <xsl:variable name="episodeNames" select="//tokens/token[@name='%EPISODENAMESLIST%']"/>
  <xsl:variable name="episodesSeparator" select="string('. &#xD;&#xA;')"/>
  <xsl:variable name="episodeNamesSeparator" select="string('&#xD;&#xA;')"/>
  <xsl:variable name="FolderJpgName" select="string('folder.jpg')"/>
  <xsl:variable name="FilePath" select="string(//tokens/token[@name='%TITLEPATH%'])"/>
  <xsl:variable name="FileName" select="string(//tokens/token[@name='%MOVIEFILENAME%'])"/>
  <xsl:variable name="TemplatePath" select="string(//tokens/token[@name='%PATH%'])"/>
  <xsl:variable name="RATING" select="string(//tokens/token[@name='%RATING%'])"/>
  <xsl:variable name="rating" select="//tokens/token[@name='%RATING%']"/>
  <xsl:variable name="AR" select="string(//tokens/token[@name='%ASPECTRATIOTEXT%'])"/>
  <xsl:variable name="MPAA" select="string(//tokens/token[@name='%MPAA%'])"/>
  <xsl:variable name="Sub1" select="string(//tokens/token[@name='%SUBTITLES1%'])"/>
  <xsl:variable name="Sub2" select="string(//tokens/token[@name='%SUBTITLES2%'])"/>
  <xsl:variable name="Sub3" select="string(//tokens/token[@name='%SUBTITLES3%'])"/>
  <xsl:variable name="Sub4" select="string(//tokens/token[@name='%SUBTITLES3%'])"/>
  <xsl:variable name="ExtSub1" select="string(//tokens/token[@name='%EXTERNALSUBTITLES1%'])"/>
  <xsl:variable name="Genre" select="string(//tokens/token[@name='%GENRES%'])"/>
  <xsl:variable name="Studios" select="string(//tokens/token[@name='%STUDIOS%'])"/>
  <xsl:variable name="Screenshot" select="string(//tokens/token[@name='%FANART3%'])"/>
  <xsl:variable name="ResolutionText" select="string(//tokens/token[@name='%RESOLUTIONTEXT%'])"/>
  <xsl:variable name="Common" select="string('\..\common\')"/>
  <xsl:variable name="Runtime" select="string(//tokens/token[@name='%RUNTIME%'] * 60)"/>
  <xsl:variable name="DurationSec" select="string(//tokens/token[@name='%DURATIONSEC%'])"/>
  <xsl:variable name="Language" select="string(//tokens/token[@name='%LANGUAGES%'])"/>
  <xsl:variable name="CERTIFICATION" select="string(//tokens/token[@name='%CERTIFICATION%'])"/>
  <!--xsl:variable name="Runtime" select="string(21 * 60)"/>
  <xsl:variable name="DurationSec" select="string('1265')"/-->
  <xsl:variable name="BACKGROUND" select="string(//tokens/token[@name='%BACKGROUND%'])"/>
  <xsl:variable name="FANART1" select="string(//tokens/token[@name='%FANART1%'])"/>
  <xsl:variable name="FANART2" select="string(//tokens/token[@name='%FANART2%'])"/>
  <xsl:variable name="FANART3" select="string(//tokens/token[@name='%FANART3%'])"/>
  <xsl:variable name="ACTORS" select="string(//tokens/token[@name='%ACTORS%'])"/>
  <xsl:variable name="ALLSUBTITLES" select="string(//tokens/token[@name='%ALLSUBTITLES%'])"/>
  <xsl:variable name="ALLSUBTITLESTEXT" select="string(//tokens/token[@name='%ALLSUBTITLESTEXT%'])"/>
  <xsl:variable name="ASPECTRATIOTEXT" select="string(//tokens/token[@name='%ASPECTRATIOTEXT%'])"/>
  <xsl:variable name="AUDIOBITRATETEXT" select="string(//tokens/token[@name='%AUDIOBITRATETEXT%'])"/>
  <xsl:variable name="AUDIOCHANNELSTEXT" select="string(//tokens/token[@name='%AUDIOCHANNELSTEXT%'])"/>
  <xsl:variable name="AUDIOCODECTEXT" select="string(//tokens/token[@name='%AUDIOCODECTEXT%'])"/>
  <xsl:variable name="CERTIFICATIONCOUNTRYCODE" select="string(//tokens/token[@name='%CERTIFICATIONCOUNTRYCODE%'])"/>
  <xsl:variable name="CERTIFICATIONTEXT" select="string(//tokens/token[@name='%CERTIFICATIONTEXT%'])"/>
  <xsl:variable name="COMMENTS" select="string(//tokens/token[@name='%COMMENTS%'])"/>
  <xsl:variable name="CONTAINERTEXT" select="string(//tokens/token[@name='%CONTAINERTEXT%'])"/>
  <xsl:variable name="COUNTRIES" select="string(//tokens/token[@name='%COUNTRIES%'])"/>
  <xsl:variable name="COVER" select="string(//tokens/token[@name='%COVER%'])"/>
  <xsl:variable name="DIRECTORS" select="string(//tokens/token[@name='%DIRECTORS%'])"/>
  <xsl:variable name="DURATION" select="string(//tokens/token[@name='%DURATION%'])"/>
  <xsl:variable name="DURATIONSEC" select="string(//tokens/token[@name='%DURATIONSEC%'])"/>
  <xsl:variable name="DURATIONTEXT" select="string(//tokens/token[@name='%DURATIONTEXT%'])"/>
  <xsl:variable name="EPISODE" select="string(//tokens/token[@name='%EPISODE%'])"/>
  <xsl:variable name="EPISODEGUESTSTARS" select="string(//tokens/token[@name='%EPISODEGUESTSTARS%'])"/>
  <xsl:variable name="EPISODELIST" select="string(//tokens/token[@name='%EPISODELIST%'])"/>
  <xsl:variable name="EPISODENAMESLIST" select="string(//tokens/token[@name='%EPISODENAMESLIST%'])"/>
  <xsl:variable name="EPISODEPLOT" select="string(//tokens/token[@name='%EPISODEPLOT%'])"/>
  <xsl:variable name="EPISODERELEASEDATE" select="string(//tokens/token[@name='%EPISODERELEASEDATE%'])"/>
  <xsl:variable name="EPISODETITLE" select="string(//tokens/token[@name='%EPISODETITLE%'])"/>
  <xsl:variable name="EPISODEWRITERS" select="string(//tokens/token[@name='%EPISODEWRITERS%'])"/>
  <xsl:variable name="EXTERNALSUBTITLES" select="string(//tokens/token[@name='%EXTERNALSUBTITLES%'])"/>
  <xsl:variable name="EXTERNALSUBTITLES1" select="string(//tokens/token[@name='%EXTERNALSUBTITLES1%'])"/>
  <xsl:variable name="EXTERNALSUBTITLES2" select="string(//tokens/token[@name='%EXTERNALSUBTITLES2%'])"/>
  <xsl:variable name="EXTERNALSUBTITLES3" select="string(//tokens/token[@name='%EXTERNALSUBTITLES3%'])"/>
  <xsl:variable name="EXTERNALSUBTITLES4" select="string(//tokens/token[@name='%EXTERNALSUBTITLES4%'])"/>
  <xsl:variable name="EXTERNALSUBTITLES5" select="string(//tokens/token[@name='%EXTERNALSUBTITLES5%'])"/>
  <xsl:variable name="EXTERNALSUBTITLESTEXT" select="string(//tokens/token[@name='%EXTERNALSUBTITLESTEXT%'])"/>
  <xsl:variable name="FILESIZETEXT" select="string(//tokens/token[@name='%FILESIZETEXT%'])"/>
  <xsl:variable name="FRAMERATE" select="string(//tokens/token[@name='%FRAMERATE%'])"/>
  <xsl:variable name="FRAMERATETEXT" select="string(//tokens/token[@name='%FRAMERATETEXT%'])"/>
  <xsl:variable name="GENRES" select="string(//tokens/token[@name='%GENRES%'])"/>
  <xsl:variable name="IMDBID" select="string(//tokens/token[@name='%IMDBID%'])"/>
  <xsl:variable name="LANGUAGE" select="string(//tokens/token[@name='%LANGUAGE%'])"/>
  <xsl:variable name="LANGUAGECODE" select="string(//tokens/token[@name='%LANGUAGECODE%'])"/>
  <xsl:variable name="LANGUAGECODES" select="string(//tokens/token[@name='%LANGUAGECODES%'])"/>
  <xsl:variable name="LANGUAGES" select="string(//tokens/token[@name='%LANGUAGES%'])"/>
  <xsl:variable name="MEDIAFORMATTEXT" select="string(//tokens/token[@name='%MEDIAFORMATTEXT%'])"/>
  <xsl:variable name="MOVIEFILENAME" select="string(//tokens/token[@name='%MOVIEFILENAME%'])"/>
  <xsl:variable name="MOVIEFILENAMEWITHOUTEXT" select="string(//tokens/token[@name='%MOVIEFILENAMEWITHOUTEXT%'])"/>
  <xsl:variable name="MOVIEFOLDER" select="string(//tokens/token[@name='%MOVIEFOLDER%'])"/>
  <xsl:variable name="MOVIEPARENTFOLDER" select="string(//tokens/token[@name='%MOVIEPARENTFOLDER%'])"/>
  <xsl:variable name="ORIGINALTITLE" select="string(//tokens/token[@name='%ORIGINALTITLE%'])"/>
  <xsl:variable name="PATH" select="string(//tokens/token[@name='%PATH%'])"/>
  <xsl:variable name="PLOT" select="string(//tokens/token[@name='%PLOT%'])"/>
  <xsl:variable name="RELEASEDATE" select="string(//tokens/token[@name='%RELEASEDATE%'])"/>
  <xsl:variable name="RESOLUTIONTEXT" select="string(//tokens/token[@name='%RESOLUTIONTEXT%'])"/>
  <xsl:variable name="RUNTIME" select="string(//tokens/token[@name='%RUNTIME%'])"/>
  <xsl:variable name="SEASON" select="string(//tokens/token[@name='%SEASON%'])"/>
  <xsl:variable name="SOUNDFORMATTEXT" select="string(//tokens/token[@name='%SOUNDFORMATTEXT%'])"/>
  <xsl:variable name="SUBTITLES" select="string(//tokens/token[@name='%SUBTITLES%'])"/>
  <xsl:variable name="SUBTITLESTEXT" select="string(//tokens/token[@name='%SUBTITLESTEXT%'])"/>
  <xsl:variable name="TAGLINE" select="string(//tokens/token[@name='%TAGLINE%'])"/>
  <xsl:variable name="TITLE" select="string(//tokens/token[@name='%TITLE%'])"/>
  <xsl:variable name="TITLEPATH" select="string(//tokens/token[@name='%TITLEPATH%'])"/>
  <xsl:variable name="VIDEOBITRATETEXT" select="string(//tokens/token[@name='%VIDEOBITRATETEXT%'])"/>
  <xsl:variable name="VIDEOCODECTEXT" select="string(//tokens/token[@name='%VIDEOCODECTEXT%'])"/>
  <xsl:variable name="VIDEOFORMATTEXT" select="string(//tokens/token[@name='%VIDEOFORMATTEXT%'])"/>
  <xsl:variable name="VIDEORESOLUTION" select="string(//tokens/token[@name='%VIDEORESOLUTION%'])"/>
  <xsl:variable name="VIDEORESOLUTIONTEXT" select="string(//tokens/token[@name='%VIDEORESOLUTIONTEXT%'])"/>
  <xsl:variable name="YEAR" select="string(//tokens/token[@name='%YEAR%'])"/>
 </xsl:stylesheet>